In [2]:
import pandas as pd
import requests
import json

In [6]:
df = pd.read_csv('911_Police_Calls_for_Service.csv')
df.info()
df.Priority.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7823490 entries, 0 to 7823489
Data columns (total 20 columns):
 #   Column                       Dtype
---  ------                       -----
 0   RecordID                     int64
 1   CallNumber                   object
 2   CallDateTime                 object
 3   Priority                     object
 4   District                     object
 5   Description                  object
 6   IncidentLocation             object
 7   ZipCode                      float64
 8   Neighborhood                 object
 9   PoliceDistrict               object
 10  PolicePost                   float64
 11  CouncilDistrict              float64
 12  SheriffDistricts             object
 13  Community_Statistical_Areas  object
 14  Census_Tracts                object
 15  VRIZones                     object
 16  Location                     object
 17  2010 Census Neighborhoods    float64
 18  2010 Census Wards Precincts  float64
 19  Zip Codes                    float64
dtypes: float64(6), int64(1), object(13)
memory usage: 1.2+ GB

array(['Medium', 'High', 'Low', 'Non-Emergency', 'Emergency',
       'Out of Service', nan], dtype=object)

In [5]:
df.Census_Tracts.unique()

array(['Census Tract 2102', 'Census Tract 2005', 'Census Tract 2605.01',
       'Census Tract 2711.01', 'Census Tract 1507.01',
       'Census Tract 2502.07', 'Census Tract 2717', 'Census Tract 2713',
       'Census Tract 2007.01', 'Census Tract 701', 'Census Tract 402',
       'Census Tract 1501', 'Census Tract 1803', 'Census Tract 2804.01',
       'Census Tract 2602.02', 'Census Tract 2403', 'Census Tract 1701',
       'Census Tract 2802', 'Census Tract 2504.01', 'Census Tract 401',
       'Census Tract 2302', 'Census Tract 2801.01', 'Census Tract 803.02',
       nan, 'Census Tract 1506', 'Census Tract 2720.05',
       'Census Tract 1510', 'Census Tract 2801.02', 'Census Tract 1604',
       'Census Tract 1608.02', 'Census Tract 1507.02',
       'Census Tract 801.01', 'Census Tract 2602.03',
       'Census Tract 2704.01', 'Census Tract 301', 'Census Tract 2301',
       'Census Tract 604', 'Census Tract 2606.05', 'Census Tract 703',
       'Census Tract 1505', 'Census Tract 2716', 'Census Tract 2805',
       'Census Tract 203', 'Census Tract 2603.01', 'Census Tract 202',
       'Census Tract 2610', 'Census Tract 1307', 'Census Tract 2609',
       'Census Tract 802', 'Census Tract 1001', 'Census Tract 2501.02',
       'Census Tract 2604.04', 'Census Tract 2602.01',
       'Census Tract 2709.02', 'Census Tract 1903', 'Census Tract 804',
       'Census Tract 2608', 'Census Tract 601', 'Census Tract 801.02',
       'Census Tract 2303', 'Census Tract 1504', 'Census Tract 2201',
       'Census Tract 904', 'Census Tract 2007.02', 'Census Tract 302',
       'Census Tract 1511', 'Census Tract 603', 'Census Tract 2707.02',
       'Census Tract 2603.02', 'Census Tract 1204', 'Census Tract 2006',
       'Census Tract 2705.01', 'Census Tract 1901',
       'Census Tract 2501.03', 'Census Tract 2704.02',
       'Census Tract 2101', 'Census Tract 2708.02',
       'Census Tract 2603.03', 'Census Tract 1302', 'Census Tract 1601',
       'Census Tract 2708.01', 'Census Tract 103', 'Census Tract 2710.02',
       'Census Tract 2701.02', 'Census Tract 2712', 'Census Tract 2002',
       'Census Tract 1902', 'Census Tract 101', 'Census Tract 2502.06',
       'Census Tract 1206', 'Census Tract 1513', 'Census Tract 704',
       'Census Tract 1402', 'Census Tract 2709.03', 'Census Tract 2402',
       'Census Tract 2604.02', 'Census Tract 1606', 'Census Tract 1003',
       'Census Tract 2719', 'Census Tract 602', 'Census Tract 2708.05',
       'Census Tract 805', 'Census Tract 2505', 'Census Tract 2606.04',
       'Census Tract 1702', 'Census Tract 2715.03',
       'Census Tract 2804.02', 'Census Tract 1605',
       'Census Tract 2710.01', 'Census Tract 908', 'Census Tract 1308.05',
       'Census Tract 1703', 'Census Tract 2001', 'Census Tract 1304',
       'Census Tract 1512', 'Census Tract 2714', 'Census Tract 2503.01',
       'Census Tract 806', 'Census Tract 1403', 'Census Tract 2504.02',
       'Census Tract 2008', 'Census Tract 1607', 'Census Tract 1802',
       'Census Tract 2715.01', 'Census Tract 2720.03', 'Census Tract 902',
       'Census Tract 1303', 'Census Tract 2718.01', 'Census Tract 104',
       'Census Tract 702', 'Census Tract 2720.06', 'Census Tract 2503.03',
       'Census Tract 1502', 'Census Tract 2506', 'Census Tract 2611',
       'Census Tract 1602', 'Census Tract 803.01', 'Census Tract 2501.01',
       'Census Tract 905', 'Census Tract 903', 'Census Tract 907',
       'Census Tract 2705.02', 'Census Tract 1608.01',
       'Census Tract 2004', 'Census Tract 1203', 'Census Tract 2707.01',
       'Census Tract 2401', 'Census Tract 1509', 'Census Tract 2720.07',
       'Census Tract 1401', 'Census Tract 2502.04', 'Census Tract 2706',
       'Census Tract 2604.01', 'Census Tract 901', 'Census Tract 909',
       'Census Tract 2708.03', 'Census Tract 1202.02',
       'Census Tract 2502.03', 'Census Tract 808', 'Census Tract 2804.04',
       'Census Tract 1308.06', 'Census Tract 1603',
       'Census Tract 1308.04', 'Census Tract 1207',
       'Census Tract 2701.01', 'Census Tract 2803.02',
       'Census Tract 1205', 'Census Tract 1002', 'Census Tract 1301',
       'Census Tract 1508', 'Census Tract 2601.01',
       'Census Tract 1308.03', 'Census Tract 2709.01',
       'Census Tract 1202.01', 'Census Tract 2718.02',
       'Census Tract 1102', 'Census Tract 2003', 'Census Tract 2604.03',
       'Census Tract 1503', 'Census Tract 1306', 'Census Tract 1101',
       'Census Tract 906', 'Census Tract 2703.01', 'Census Tract 1201',
       'Census Tract 2707.03', 'Census Tract 201', 'Census Tract 2803.01',
       'Census Tract 2601.02', 'Census Tract 2702', 'Census Tract 105',
       'Census Tract 1801', 'Census Tract 2607', 'Census Tract 2502.05',
       'Census Tract 807', 'Census Tract 2720.04', 'Census Tract 2703.02',
       'Census Tract 2804.03', 'Census Tract 102', 'Census Tract 2404',
       'Census Tract 2708.04', 'Census Tract 2711.02'], dtype=object)

In [57]:
api_token = '827add90f9f79abed8f3344cf60ee0ee09d6c7e6'
api_url_base = 'https://api.census.gov/data/2018/acs/acs5/profile'

#'https://api.census.gov/data/2018/acs/acs5/profile/'

In [60]:
parameter = {"get":"DP04_0001E,DP04_0002E,DP04_0003E,DP04_0016E,DP04_0027E,DP04_0037E,DP04_0050E,DP04_0057E,DP04_0080E,DP04_0090E,DP04_0093E",
             "key":api_token,"for":'tract:*',"in":'state:01'}
request = requests.get(api_url_base,parameter)
#print(request.text)
rhyme_json = request.json()
writeFile =open('file_name.json', 'w')
#writeFile.write(rhyme_json)
with open('file_name.json', 'w', encoding='utf-8') as f:
    json.dump(rhyme_json, f, ensure_ascii=False, indent=4)
writeFile.close()
pd.read_json('file_name.json') #_, orient='split'

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,DP04_0001E,DP04_0002E,DP04_0003E,DP04_0016E,DP04_0027E,DP04_0037E,DP04_0050E,DP04_0057E,DP04_0080E,DP04_0090E,DP04_0093E,state,county,tract
1,1327,1004,323,1327,1327,5.9,1004,1004,590,590,226,01,073,005701
2,1498,1249,249,1498,1498,5.2,1249,1249,593,593,444,01,073,010704
3,2182,2118,64,2182,2182,4.5,2118,2118,833,833,562,01,073,012908
4,1656,1495,161,1656,1656,6.7,1495,1495,1175,1175,721,01,073,005302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,2537,2226,311,2537,2537,5.8,2226,2226,1626,1626,1284,01,125,012502
1178,1241,1101,140,1241,1241,5.4,1101,1101,709,709,315,01,097,006802
1179,1475,1305,170,1475,1475,5.9,1305,1305,1105,1105,631,01,097,007103
1180,717,593,124,717,717,5.4,593,593,460,460,320,01,125,012501
1181,1497,725,772,1497,1497,4.6,725,725,132,132,69,01,125,012600